# Generated by Django 6.0.1 on 2026-01-15 21:58

import turnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nombre Cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('date_time', models.DateTimeField(validators=[turnos.models.validar_fecha_futura], verbose_name='Fecha y Hora')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('whatsapp_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
